# -*- coding: utf-8 -*-
"""home

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ttdh8Lc5Zs_j_UNUzwHIJWD8AojsDAcw
"""

import streamlit as st

st.set_page_config(page_title="Safra do café", page_icon="☕", layout="wide")

st.title("☕ SAFRA DO CAFÉ")
st.write("Sistema avançado de previsão da safra do café com uso de imagens de satélite (sensor MSI/Sentinel-2A) e Machine Learning")

st.markdown("""
Use o menu lateral para navegar entre as etapas do projeto:

1. Área Amostral Total
2. Pré-processamento dos dados
3. Índices de Vegetação
4. Modelagem
""")